---
- name: General Config for Routers
  hosts: routers
  gather_facts: true  
  vars:
    hostname: "{{ inventory_hostname }}"
  vars_files:
    - pass.yml
  tasks:
    # - name: Add Banner
    #   cisco.ios.ios_banner:
    #     banner: login
    #     text: |
    #       Wasssssssssssuuuuuuuuuup
    #     state: present

    - name: Get timestamp
      command: date +%Y-%m-%d
      register: timestamp

    - name: Get router running config
      cisco.ios.ios_command:
        commands: show running-config
      register: router_config

    - name: Save config to local temp file
      ansible.builtin.copy:
        content: "{{ router_config.stdout[0] }}"
        dest: "/tmp/back/{{ inventory_hostname }}_{{ timestamp.stdout }}.cfg"
      delegate_to: localhost

    - name: Copy file 
      shell: |
        sshpass -p "123" sftp souhail_backup@192.168.11.165 <<EOF
        put /tmp/back/{{ inventory_hostname }}_{{ timestamp.stdout }}.cfg  /home/storage/backup/cisco/RT
        exit
        EOF


- name: Backup Switch Config 
  hosts: switches
  gather_facts: no

  tasks:
    - name: Get timestamp
      command: date +%Y-%m-%d
      register: timestamp
      delegate_to: localhost
    
    - name: Get switch running config
      cisco.ios.ios_command:
        commands: show running-config
      register: switch_config
    
    - name: Save config to local temp file
      ansible.builtin.copy:
        content: "{{ switch_config.stdout[0] }}"
        dest: "/tmp/back/{{ inventory_hostname }}_{{ timestamp.stdout }}.cfg"
      delegate_to: localhost


    # - name: Copy file using sftp
    #   shell: |
    #     echo "put /tmp/{{ inventory_hostname }}_{{ timestamp.stdout }}.cfg /home/storage/backup/" | sftp souhail_backup@192.168.11.165

    - name: Copy file 
      shell: |
        sshpass -p "123" sftp souhail_backup@192.168.11.165 <<EOF
        put /tmp/back/{{ inventory_hostname }}_{{ timestamp.stdout }}.cfg  /home/storage/backup/cisco/SW
        exit
        EOF
    
  
  
