---
- name: Backup Dell OS10 Switch Configuration
  hosts: dell  
  gather_facts: no 

  tasks:
    - name: Get timestamp
      command: date +%Y-%m-%d
      register: timestamp

    - name: Backup current switch config (dellos10)
      dellemc.os10.os10_config:
        backup: yes
        backup_options:
          dir_path: "/etc/ansible/dell_folder"
          filename: "{{ inventory_hostname }}_{{ timestamp.stdout }}.cfg"
      register: backup_dellos10_location
      when: ansible_network_os == 'dellemc.os10.os10'

    - name: Display backup location
      debug:
        msg: "Backup stored at {{ backup_dellos10_location.backup_path }}"
      when: backup_dellos10_location.backup_path is defined


    - name: Copy file 
      shell: |
        sshpass -p "123" sftp souhail_backup@192.168.11.165 <<EOF
        put /etc/ansible/dell_folder/{{inventory_hostname}}_{{ timestamp.stdout }}.cfg  /home/storage/backup/dell
        exit
        EOF
      no_log: true 