---
- name: Export PA configs
  hosts: paloAltos
  connection: local
  gather_facts: no
  strategy: linear

  tasks:
    - name: Get timestamp
      command: date +%Y-%m-%d
      register: timestamp

    - name: Get REST API Key
      uri:
        validate_certs: no
        url: 'https://{{ ansible_host }}/api/?type=keygen&user={{ pa_rest_user }}&password={{ pa_rest_password }}'
        return_content: yes
        method: GET
      register: response_api_key

    - name: Read XML response
      xml: 
        content: 'text'
        xmlstring: '{{ response_api_key.content }}'
        xpath: '/response/result/key'
      register: api_key 

    - name: Gather config
      uri:
        validate_certs: no
        url: 'https://{{ ansible_host }}/api/?type=config&action=show&key={{ api_key.matches[0].key }}'
        return_content: yes
      register: response_pa_config

    - name: Save initial config
      copy:
        content: "{{ response_pa_config.content }}"
        dest: "/etc/ansible/palo_folder/{{ inventory_hostname }}_{{ timestamp.stdout }}.xml"

    - name: Remove unwanted closing tags
      replace:
        path: "/etc/ansible/palo_folder/{{ inventory_hostname }}_{{ timestamp.stdout }}.xml"
        regexp: '</result></response>'
        replace: ''

    - name: Remove extra newlines at end of file
      shell: |
        sed -i -e :a -e '/^\n*$/{$d;N;ba' -e '}' "/etc/ansible/palo_folder/{{ inventory_hostname }}_{{ timestamp.stdout }}.xml"

    - name: Copy file 
      shell: |
        sshpass -p "123" sftp souhail_backup@192.168.11.165 <<EOF
        put /etc/ansible/palo_folder/{{ inventory_hostname }}_{{ timestamp.stdout }}.xml  /home/storage/backup/palo
        exit
        EOF
      no_log: true 